Ben/lmb 461 nb members bestuursorgaan
lblod/mandataris-service pull request #27
Opened 2024-07-16 08:42 UTC by bfidlers

## Description

Add a query to get the nb of active mandatarissen of a mandate.

## How to test

See frontend.

## Links to other PR's

- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/276

2024-07-18 14:00 UTC, JonasVanHoof approved these changes
Looks good

2024-07-18 14:19 UTC, JonasVanHoof requested changes
q

2024-08-05 06:42 UTC, JonasVanHoof reviewed
The code looks ok imo but I still get irrregulties with gemeenteraadsleden in an orgaan

2024-08-14 07:16 UTC, Rahien approved these changes

2024-08-14 07:18 UTC, merged