LMB-607 | The besluit does not have to be added to the mandataris anymore
lblod/mandataris-service pull request #41
Opened 2024-08-27 13:31 UTC by JonasVanHoof

## Description

As we updated the mandataris/besluit/artikel model we do not have to set the besluit on the  mandataris anymore. When a decision is found for the mandataris the publication status is set to BEKRACHTIGD.

## How to test

REmoved logic for adding the besluit to the mandataris, this logic will again be tested in LMB-666

## Links to other PR's

- https://github.com/lblod/app-lokaal-mandatenbeheer/pull/194 => app
- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/311 => frontend

2024-08-27 13:50 UTC, Rahien requested changes

2024-08-27 13:50 UTC, Rahien commented on controllers/mandatees-decisions.ts
while you're at it, can you fix some of the typos here?

dicision, doe snot, and PUBLICATION_STATUS.BEKRACHTIGT (should be d) are some that i see

2024-08-27 13:50 UTC, Rahien commented on controllers/mandatees-decisions.ts
:deer: :sneezing_face:

2024-08-27 13:50 UTC, Rahien commented on controllers/mandatees-decisions.ts
I also noticed that findDecisionForMandataris uses the incorrect ext: prefix for bekrachtigtAanstellingVan. It should be mandaat.

2024-08-27 14:08 UTC, JonasVanHoof commented on controllers/mandatees-decisions.ts
Does ABB provide us with language lessons?

Also added a todo to look for mandaat:bekractigdOntslagVan

2024-09-05 11:35 UTC, Rahien approved these changes

2024-09-05 11:35 UTC, merged